import pandas as pd
from sqlalchemy import create_engine, text


# ---------------------------------------
# MySQL connection
# ---------------------------------------

username = "root"
password = "1404"
host = "localhost"
port = 3306
database = "text_to_sql"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)


# ---------------------------------------
# SQL generated by Mistral
# ---------------------------------------

sql = """
SELECT
    customer_id,
    customer_name,
    SUM(sales) AS total_sales
FROM sales_data
GROUP BY customer_id, customer_name
ORDER BY total_sales DESC
LIMIT 10;
"""


# ---------------------------------------
# Execute query
# ---------------------------------------

with engine.connect() as connection:

    result = pd.read_sql(
        text(sql),
        connection
    )


# ---------------------------------------
# Display results
# ---------------------------------------

print("\nTop 10 Customers:")
print(result.to_string(index=False))